_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VINSERTF128,",
    offsets = "0,16,",
    addresses = "0x1730,0x1735,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VINSERTF128,",
    offsets = "0,16,",
    addresses = "0x173d,0x1742,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VINSERTF128,",
    offsets = "0,16,",
    addresses = "0x174f,0x1754,",
    stride_status = "Success",
    stride = 32,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 32,
    unroll_factor = 1,
  },
}
